// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwDKkC4UKjgWD93ka9MnxovoxYxe1pnA',
    appId: '1:748148779651:web:c0837a56409f87330a09b6',
    messagingSenderId: '748148779651',
    projectId: 'biblioteca-escolar-feli2099',
    authDomain: 'biblioteca-escolar-feli2099.firebaseapp.com',
    storageBucket: 'biblioteca-escolar-feli2099.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkSWXJU7KL6pnywTcSpOtDlNc6P9p4v2U',
    appId: '1:748148779651:android:513d7e468cc3f0130a09b6',
    messagingSenderId: '748148779651',
    projectId: 'biblioteca-escolar-feli2099',
    storageBucket: 'biblioteca-escolar-feli2099.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1yViy3Z-6EWCZt_qyPaPZ9JF0i-x7yI',
    appId: '1:748148779651:ios:cb6654c789a63c760a09b6',
    messagingSenderId: '748148779651',
    projectId: 'biblioteca-escolar-feli2099',
    storageBucket: 'biblioteca-escolar-feli2099.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaEscolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1yViy3Z-6EWCZt_qyPaPZ9JF0i-x7yI',
    appId: '1:748148779651:ios:cb6654c789a63c760a09b6',
    messagingSenderId: '748148779651',
    projectId: 'biblioteca-escolar-feli2099',
    storageBucket: 'biblioteca-escolar-feli2099.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaEscolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXwDKkC4UKjgWD93ka9MnxovoxYxe1pnA',
    appId: '1:748148779651:web:31c23f0e3a5de8020a09b6',
    messagingSenderId: '748148779651',
    projectId: 'biblioteca-escolar-feli2099',
    authDomain: 'biblioteca-escolar-feli2099.firebaseapp.com',
    storageBucket: 'biblioteca-escolar-feli2099.firebasestorage.app',
  );
}
